### ISSUE TITLE
Ingest user account data which have access to control.akamai.com

### ISSUE THREAD

**Issue by ccloes** [nodestream-proj/nodestream-plugin-akamai#24]
We need to monitor for users who have access to akamai.  We need to ingest the necessary data associated with detecting the following.

* Do we allow non-sso enabled users?
* Ingest users who have access to akamai (via control.akamai.com, or via api)
* Identify if those accounts/api keys have been accessed
* Identify if those keys need to be rotated (90 day policy)

**Comment by stuartio** [comment]
#33

**Comment by ccloes** [comment]
Closed by this PR: https://github.com/nodestream-proj/nodestream-plugin-akamai/pull/33
