### ISSUE TITLE
Ingest user account data which have access to netstorage

### ISSUE THREAD

**Issue by ccloes** [nodestream-proj/nodestream-plugin-akamai#25]
We need to monitor for users who have access to netstorage. We need to ingest the necessary data associated with detecting the following.

* Ingest users who have access to netstorage including (creation dates, expiration dates)
* What access they have
* What the status of their "keys"
* Any other auth related netstorage data which is relevant to audit netstorage users access and rotation

**Comment by stuartio** [comment]
These changes have been merged. This one can be closed

**Comment by ccloes** [comment]
Closed this with this PR: https://github.com/nodestream-proj/nodestream-plugin-akamai/pull/16
