### ISSUE TITLE
Plugin requires Read/Write access to Property API

### ISSUE THREAD

**Issue by stuartio** [nodestream-proj/nodestream-plugin-akamai#45]
Property bulk search API is a POST request, which requires Read/Write access to the API. Therefore to efficiently search properties you need much higher rights than it should.

Options are:
- Rewrite plugin to only use GET operations
- Get Akamai engineering to fix the API permissions

**Comment by ccloes** [comment]
Closed by this PR: https://github.com/nodestream-proj/nodestream-plugin-akamai/pull/47
