### ISSUE TITLE
We need to include "Created" and "Expiration" for AkamaiIamClient Nodes

### ISSUE THREAD

**Issue by ccloes** [nodestream-proj/nodestream-plugin-akamai#54]
To properly enable key rotation, we need to know the dates associated with Akamai client keys 

<img width="1396" alt="image" src="https://github.com/nodestream-proj/nodestream-plugin-akamai/assets/1000538/1ef29331-8057-4fb3-b5a9-5aabbafd7096">

**Comment by stuartio** [comment]
#55
